### ISSUE TITLE
Impossible to not use keychain

### ISSUE THREAD

**Issue by djmitche** [mozilla/inv-tool#13]
If I remove all parts of the `[authorization]` config:

```
(moz)dustin@euclid ~/code/moz/t/invtool [more-config*] $ invtool search -q releng-puppet
ldap username: dmitchell@mozilla.com
password:
Please input your password for the keyring
```

so, it's trying to set up a keyring for me :(

**Comment by djmitche** [comment]
In fact, it's impossible to specify a password in the config file, too - that prompts me for my username as well.

**Comment by djmitche** [comment]
This appears to be because if `keyring` is installed (which it is, as a dependency) then it does not allow non-keyring behaviors.

**Comment by uberj** [comment]
I've attempted to address these issues with this commit: f08b4d6352c1fc0d2c101062fd39861debc8631a

Here is some test output of me changing the options under the `[authorization]` section in my config file, then asking invtool which auth method it wants to use:

```
» cat etc/invtool.conf | grep -A 2 "authorization"
[authorization]
keyring = invtool-ldap
ldap_username = me@mozilla.com

» ./inv status | grep AUTH_TYPE
AUTH_TYPE: keyring

» cat etc/invtool.conf | grep -A 2 "authorization"
[authorization]
ldap_username = me@mozilla.com

» ./inv status | grep AUTH_TYPE
AUTH_TYPE: plaintext

» cat etc/invtool.conf | grep -A 2 "authorization"
[authorization]
keyring = invtool-ldap

» ./inv status | grep AUTH_TYPE
AUTH_TYPE: keyring

» cat etc/invtool.conf | grep -A 2 "authorization"
[authorization]
ldap_password = password
ldap_username = me@mozilla.com

» ./inv status | grep AUTH_TYPE
AUTH_TYPE: plaintext

» cat etc/invtool.conf | grep -A 2 "authorization"
[authorization]

» ./inv status | grep AUTH_TYPE
AUTH_TYPE: plaintext
```

**Comment by djmitche** [comment]
The demo looks good - if this is merged, then let's close it up.
